services:
  server:
    image: vantinh2292/scada_server:latest
    container_name: server
    networks:
      - my_network
    restart: always
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
      - NODE_RED_ENABLE_CRYPTO=false
    deploy:
      resources:
        limits:
          cpus: "2.0"  # Limit to 2 CPU cores
          memory: "4G"  # Limit to 4 GB of memory
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - D:/OneDrive/Desktop/Docker_Scada/docker_scada/server/db:/server/db  
      - D:/OneDrive/Desktop/Docker_Scada/docker_scada/server/userDir:/server/userDir
      - D:/OneDrive/Desktop/Docker_Scada/docker_scada/server/dist:/server/dist
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  client:
    image: vantinh2292/scada_client:latest
    container_name: client
    depends_on:
      - server
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - D:/OneDrive/Desktop/Docker_Scada/docker_scada/client/config.json:/client/public/config.json
      - D:/OneDrive/Desktop/Docker_Scada/docker_scada/client/.next:/client/.next
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 8002:8002
      - 3001:3001
      - 1884:1884 #MQTT_PORT
      - 8084:8084 #MQTT_WS_PORT

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  my_network:
    driver: bridge
