services:
  server:
    image: vantinh2292/scada_server:latest
    container_name: server
    networks:
      - mynetwork
    # restart: always
    ports:
      - "${DOCKER_SERVER_PORT}:${DOCKER_SERVER_INTERNAL_PORT}"
      - "${DOCKER_MQTT_PORT}:${DOCKER_MQTT_INTERNAL_PORT}"
      - "${DOCKER_MQTT_WS_PORT}:${DOCKER_MQTT_WS_INTERNAL_PORT}"
      - 9600:9600
      - 502:502

    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - D:/OneDrive/Desktop/Docker_Scada/docker_scada/server/db:/server/db  
      - D:/OneDrive/Desktop/Docker_Scada/docker_scada/server/userDir:/server/userDir
      - D:/OneDrive/Desktop/Docker_Scada/docker_scada/server/dist:/server/dist
      - D:/OneDrive/WORK/WebScada/nest-js_server/myPackage:/server/myPackage

  client:
    image: vantinh2292/scada_client:latest
    container_name: client
    depends_on:
      - server
    ports:
      - "${DOCKER_CLIENT_PORT}:${DOCKER_CLIENT_INTERNAL_PORT}"
    networks:
      - mynetwork
    # restart: always
    volumes:
      - D:/OneDrive/Desktop/Docker_Scada/docker_scada/client/config.json:/client/public/config.json
      - D:/OneDrive/Desktop/Docker_Scada/docker_scada/client/.next:/client/.next

networks:
  mynetwork:
    driver: bridge
